#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/bookshop_test
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: false
#
#app:
#  domain: http://test.ptit.dpdns.org:8080
