version: '3.8'

services:
  database-mysql:
    container_name: database-app
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: bookshop
      MYSQL_USER: appuser
      MYSQL_PASSWORD: 123456
    volumes:
      - ./mysql-ptit:/docker-entrypoint-initdb.d
    restart: always