version: "3.8"

services:
  backend-spring:
    container_name: backend-app
    image: toannd135/bookshop-backend:v4
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: development
      JAVA_OPTS: "-Xms256m -Xmx512m"
    restart: always
